In [2]:
import pandas as pd

# read the csv file
df = pd.read_csv("tagcount.csv")
print(type(df))
# view the first few rows of data
df.head()

<class 'pandas.core.frame.DataFrame'>

,TIME,CONTAINERID,CREATED,IMAGE,LABELS,MOUNTS,NAME,OID,ONAME,OS_ARCH,...,NETWORK_RDROPPED,NETWORK_RERROR,NETWORK_RIOPS,NETWORK_WBPS,NETWORK_WDROPPED,NETWORK_WERROR,NETWORK_WIOPS,RESTART_COUNT,STATE,STATUS
0,1621325281000,05b4a1a9b95ac19404ae2246d15ac5dc622ca237a25e2b...,1535014134,new_demo,NaN,/var/lib/docker/volumes/home/_data=/home,/demo1,-48826581,python-demo-target,amd64,...,0,0,0,0,0,0,0,0,running,Up 11 days
1,1621325281000,7a37ce4af9f845cb85d2d78f6c44cb304b7a9162d00a31...,1535013742,new_demo,NaN,/var/lib/docker/volumes/home/_data=/home,/demo3,-48826581,python-demo-target,amd64,...,0,0,0,0,0,0,0,0,running,Up 11 days
2,1621325281000,f57d10b8c48cdd04bba0fea5f7d1f1baedd9af4dd507db...,1535013736,new_demo,NaN,/var/lib/docker/volumes/home/_data=/home,/demo2,-48826581,python-demo-target,amd64,...,0,0,0,0,0,0,0,0,running,Up 11 days
3,1621325286000,05b4a1a9b95ac19404ae2246d15ac5dc622ca237a25e2b...,1535014134,new_demo,NaN,/var/lib/docker/volumes/home/_data=/home,/demo1,-48826581,python-demo-target,amd64,...,0,0,0,0,0,0,0,0,running,Up 11 days
4,1621325286000,7a37ce4af9f845cb85d2d78f6c44cb304b7a9162d00a31...,1535013742,new_demo,NaN,/var/lib/docker/volumes/home/_data=/home,/demo3,-48826581,python-demo-target,amd64,...,0,0,0,0,0,0,0,0,running,Up 11 days

In [3]:
import requests

response = requests.get("https://min-api.cryptocompare.com/data/histodayfsym=ETC&tsym=USD&limit=10&aggregate=3&e=CCCAGG") 


print(type(response.json()))
pd.DataFrame.from_dict(response.json())

<class 'dict'>

Empty DataFrame
Columns: [Response, Message, Type, Data]
Index: []